<a href="https://colab.research.google.com/github/DevKumar57-67/PROJECT-FIESTA-AI/blob/main/Pandas_Tutorials.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PANDAS TUTORIALS

In [ ]:
# This file is teaches Pandas python Library from scratch to advanced
# If Numpy is the math then pandas is the math applied on data
# Pandas is the backbone of data analysis

In [ ]:
# installing pandas
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
# importing pandas with pd as alias
import pandas as pd

In [ ]:
# A series
data = [10,20,30,40,50]
s = pd.Series(data)
print(s)

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [ ]:
data = {
    "Name": ["Dev", "Aryan", "Riya"],
    "Age": [20, 21, 19],
    "Marks": [90, 85, 95],
    "Game": ["Pubg", "Valorant", "Free fire"]
}

df = pd.DataFrame(data)
print(df)

    Name  Age  Marks       Game
0    Dev   20     90       Pubg
1  Aryan   21     85   Valorant
2   Riya   19     95  Free fire

In [ ]:
df.head()      # first 5 rows

    Name  Age  Marks       Game
0    Dev   20     90       Pubg
1  Aryan   21     85   Valorant
2   Riya   19     95  Free fire

In [ ]:
df.tail() # bottom 5 rows

    Name  Age  Marks       Game
0    Dev   20     90       Pubg
1  Aryan   21     85   Valorant
2   Riya   19     95  Free fire

In [ ]:
df.shape # number of rows and columns

(3, 4)

In [ ]:
#
df.columns    # column names

Index(['Name', 'Age', 'Marks', 'Game'], dtype='object')

In [ ]:
df.info() # structure of dataset

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      object
 1   Age     3 non-null      int64
 2   Marks   3 non-null      int64
 3   Game    3 non-null      object
dtypes: int64(2), object(2)
memory usage: 228.0+ bytes

In [ ]:
df.describe() # summary of dataset

        Age  Marks
count   3.0    3.0
mean   20.0   90.0
std     1.0    5.0
min    19.0   85.0
25%    19.5   87.5
50%    20.0   90.0
75%    20.5   92.5
max    21.0   95.0

In [ ]:
# Now adding the actual dataset

import pandas as pd

# Using the read_csv function for reading a CSV file
data = pd.read_csv("/content/sample_data/california_housing_train.csv")
print(data)

       longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -114.31     34.19                15.0       5612.0          1283.0
1        -114.47     34.40                19.0       7650.0          1901.0
2        -114.56     33.69                17.0        720.0           174.0
3        -114.57     33.64                14.0       1501.0           337.0
4        -114.57     33.57                20.0       1454.0           326.0
...          ...       ...                 ...          ...             ...
16995    -124.26     40.58                52.0       2217.0           394.0
16996    -124.27     40.69                36.0       2349.0           528.0
16997    -124.30     41.84                17.0       2677.0           531.0
16998    -124.30     41.80                19.0       2672.0           552.0
16999    -124.35     40.54                52.0       1820.0           300.0

       population  households  median_income  median_house_value
0          1015.0       472.0         1.4936             66900.0
1          1129.0       463.0         1.8200             80100.0
2           333.0       117.0         1.6509             85700.0
3           515.0       226.0         3.1917             73400.0
4           624.0       262.0         1.9250             65500.0
...           ...         ...            ...                 ...
16995       907.0       369.0         2.3571            111400.0
16996      1194.0       465.0         2.5179             79000.0
16997      1244.0       456.0         3.0313            103600.0
16998      1298.0       478.0         1.9797             85800.0
16999       806.0       270.0         3.0147             94600.0

[17000 rows x 9 columns]

In [ ]:
data.head() #top 5 rows

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0

In [ ]:
data.tail() # bottom 5 rows

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0

In [ ]:
data.shape # rows and columns

(17000, 9)

In [ ]:
data.describe() #structure of the dataset

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000
mean,-119.562108,35.625225,28.589353,2643.664412,539.410824,1429.573941,501.221941,3.883578,207300.912353
std,2.005166,2.137340,12.586937,2179.947071,421.499452,1147.852959,384.520841,1.908157,115983.764387
min,-124.350000,32.540000,1.000000,2.000000,1.000000,3.000000,1.000000,0.499900,14999.000000
25%,-121.790000,33.930000,18.000000,1462.000000,297.000000,790.000000,282.000000,2.566375,119400.000000
50%,-118.490000,34.250000,29.000000,2127.000000,434.000000,1167.000000,409.000000,3.544600,180400.000000
75%,-118.000000,37.720000,37.000000,3151.250000,648.250000,1721.000000,605.250000,4.767000,265000.000000
max,-114.310000,41.950000,52.000000,37937.000000,6445.000000,35682.000000,6082.000000,15.000100,500001.000000

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17000 entries, 0 to 16999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           17000 non-null  float64
 1   latitude            17000 non-null  float64
 2   housing_median_age  17000 non-null  float64
 3   total_rooms         17000 non-null  float64
 4   total_bedrooms      17000 non-null  float64
 5   population          17000 non-null  float64
 6   households          17000 non-null  float64
 7   median_income       17000 non-null  float64
 8   median_house_value  17000 non-null  float64
dtypes: float64(9)
memory usage: 1.2 MB

In [ ]:
data.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value'],
      dtype='object')

In [ ]:

# Reading the excel dataset

xcel = pd.read_excel("/content/Cola.xlsx")
xcel

,Data provided by SimFin,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Profit & Loss statement,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,in million USD,FY '09,FY '10,FY '11,FY '12,FY '13,FY '14,FY '15,FY '16,FY '17,FY '18
3,NaN,NET OPERATING REVENUES,30990,35119,46542,48017,46854,45998,44294,41863,35410,31856
4,NaN,Cost of goods sold,11088,12693,18215,19053,18421,17889,17482,16465,13255,11770
...,...,...,...,...,...,...,...,...,...,...,...,...
98,NaN,Effect of exchange rate changes on cash and ca...,576,-166,-430,-255,-611,-934,-878,-6,241,-262
99,NaN,Cash Provided by (Used in) Investing Activitie...,NaN,NaN,NaN,NaN,NaN,NaN,0,0,-58,-421
100,NaN,Cash Provided by (Used in) Financing Activitie...,NaN,NaN,NaN,NaN,NaN,NaN,0,0,-38,205
101,NaN,Net Cash Provided by (Used in) Discontinued Op...,NaN,NaN,NaN,NaN,NaN,NaN,0,0,15,91
102,NaN,Net increase (decrease) during the year,2320,1496,4286,-4361,1972,-1456,-1649,1246,-2477,2945

In [ ]:
xcel.head()

,Data provided by SimFin,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Profit & Loss statement,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,in million USD,FY '09,FY '10,FY '11,FY '12,FY '13,FY '14,FY '15,FY '16,FY '17,FY '18
3,NaN,NET OPERATING REVENUES,30990,35119,46542,48017,46854,45998,44294,41863,35410,31856
4,NaN,Cost of goods sold,11088,12693,18215,19053,18421,17889,17482,16465,13255,11770

In [ ]:
xcel.tail()

,Data provided by SimFin,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
98,NaN,Effect of exchange rate changes on cash and ca...,576,-166,-430,-255,-611,-934,-878,-6,241,-262
99,NaN,Cash Provided by (Used in) Investing Activitie...,NaN,NaN,NaN,NaN,NaN,NaN,0,0,-58,-421
100,NaN,Cash Provided by (Used in) Financing Activitie...,NaN,NaN,NaN,NaN,NaN,NaN,0,0,-38,205
101,NaN,Net Cash Provided by (Used in) Discontinued Op...,NaN,NaN,NaN,NaN,NaN,NaN,0,0,15,91
102,NaN,Net increase (decrease) during the year,2320,1496,4286,-4361,1972,-1456,-1649,1246,-2477,2945

In [ ]:
xcel.shape

(103, 12)

In [ ]:
xcel.describe()

,Data provided by SimFin,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
count,3,97,82,82,82,82,82,82,90,92,93,93
unique,3,90,77,77,77,77,77,78,79,78,87,86
top,Profit & Loss statement,in million USD,FY '09,FY '10,FY '11,FY '12,FY '13,FY '14,0,0,FY '17,FY '18
freq,1,3,3,3,3,3,3,3,6,8,3,3

In [ ]:
xcel.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103 entries, 0 to 102
Data columns (total 12 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Data provided by SimFin  3 non-null      object
 1   Unnamed: 1               97 non-null     object
 2   Unnamed: 2               82 non-null     object
 3   Unnamed: 3               82 non-null     object
 4   Unnamed: 4               82 non-null     object
 5   Unnamed: 5               82 non-null     object
 6   Unnamed: 6               82 non-null     object
 7   Unnamed: 7               82 non-null     object
 8   Unnamed: 8               90 non-null     object
 9   Unnamed: 9               92 non-null     object
 10  Unnamed: 10              93 non-null     object
 11  Unnamed: 11              93 non-null     object
dtypes: object(12)
memory usage: 9.8+ KB

In [ ]:

# Reading the Json dataset
jdat = pd.read_json("/content/sample_data/anscombe.json")
jdat

   Series   X      Y
0       I  10   8.04
1       I   8   6.95
2       I  13   7.58
3       I   9   8.81
4       I  11   8.33
5       I  14   9.96
6       I   6   7.24
7       I   4   4.26
8       I  12  10.84
9       I   7   4.81
10      I   5   5.68
11     II  10   9.14
12     II   8   8.14
13     II  13   8.74
14     II   9   8.77
15     II  11   9.26
16     II  14   8.10
17     II   6   6.13
18     II   4   3.10
19     II  12   9.13
20     II   7   7.26
21     II   5   4.74
22    III  10   7.46
23    III   8   6.77
24    III  13  12.74
25    III   9   7.11
26    III  11   7.81
27    III  14   8.84
28    III   6   6.08
29    III   4   5.39
30    III  12   8.15
31    III   7   6.42
32    III   5   5.73
33     IV   8   6.58
34     IV   8   5.76
35     IV   8   7.71
36     IV   8   8.84
37     IV   8   8.47
38     IV   8   7.04
39     IV   8   5.25
40     IV  19  12.50
41     IV   8   5.56
42     IV   8   7.91
43     IV   8   6.89

In [ ]:
jdat.head()

  Series   X     Y
0      I  10  8.04
1      I   8  6.95
2      I  13  7.58
3      I   9  8.81
4      I  11  8.33

In [ ]:
jdat.tail()

   Series   X      Y
39     IV   8   5.25
40     IV  19  12.50
41     IV   8   5.56
42     IV   8   7.91
43     IV   8   6.89

In [ ]:
jdat.shape

(44, 3)

In [ ]:
jdat.columns

Index(['Series', 'X', 'Y'], dtype='object')

In [ ]:
jdat.describe()

               X          Y
count  44.000000  44.000000
mean    9.000000   7.500455
std     3.198837   1.959244
min     4.000000   3.100000
25%     7.000000   6.117500
50%     8.000000   7.520000
75%    11.000000   8.747500
max    19.000000  12.740000

In [ ]:
jdat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44 entries, 0 to 43
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Series  44 non-null     object
 1   X       44 non-null     int64
 2   Y       44 non-null     float64
dtypes: float64(1), int64(1), object(1)
memory usage: 1.2+ KB

In [ ]:
# Data Analysis